# Generated by Django 4.1 on 2025-02-14 09:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_userprofile_charater_userprofile_desc'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='charater',
            new_name='character',
        ),
    ]
