# Generated by Django 4.1 on 2025-02-15 03:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_rename_charater_userprofile_character'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='nick_name',
        ),
    ]
