# Generated by Django 4.1 on 2025-02-15 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_sidebar'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='pv',
            field=models.PositiveIntegerField(default=0, verbose_name='浏览量'),
        ),
    ]
